name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        env:
          TFHCLEDIT_VERSION: 0.2.15
        run: |
          curl -Lo ./hcledit.tar.gz https://github.com/minamijoyo/hcledit/releases/download/v${{ env.TFHCLEDIT_VERSION }}/hcledit_${{ env.TFHCLEDIT_VERSION }}_$(uname)_amd64.tar.gz && tar -xzf hcledit.tar.gz hcledit && chmod +x hcledit && sudo mv hcledit /usr/bin/

      - name: Pre-release
        uses: cycjimmy/semantic-release-action@v4
        id: dry_release
        with:
          semantic_version: 23.0.2
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Check version in locals is the latest
        run: |
          CURRENT_VERSION=$(cat locals.tf | hcledit attribute get locals.module_version)
          echo $CURRENT_VERSION
          if [ "${{steps.dry_release.outputs.new_release_version}}" = $CURRENT_VERSION ]; then
            echo "Releasing version ${{steps.dry_release.outputs.new_release_version}}."
          elif [ "${{steps.dry_release.outputs.new_release_version}}" = "" ]; then
            echo "No release to be triggered by this merge, skipping check"
          else
            echo "Please make sure to update module_version in locals.tf with the new release version ${{steps.dry_release.outputs.new_release_version}}."
            exit 1
          fi

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{secrets.SEMANTIC_RELEASE_TOKEN}}
