name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Pre-release
        uses: cycjimmy/semantic-release-action@v4
        id: dry_release
        with:
          semantic_version: 23.0.2
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Inject new version in configuration
        run: |
          if [ "${{steps.dry_release.outputs.last_release_version}}" != "" ]; then
            echo "Updating version to ${{steps.dry_release.outputs.new_release_version}}."
            sed -i -e 's/${{steps.dry_release.outputs.last_release_version}}/${{steps.dry_release.outputs.new_release_version}}/' locals.tf
            git config --global user.email "werner@nops.io"
            git config --global user.name "Auto"
            git commit -am "bumping version in module [skip ci]"
          else
            echo "No version to update."
          fi

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{secrets.SEMANTIC_RELEASE_TOKEN}}
