name: Update locals file

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  update_locals:
    name: Update locals
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # - name: Remove releaserc file
      #   run: |
      #     rm .releaserc.json

      - name: Pre-release
        uses: cycjimmy/semantic-release-action@v4
        id: dry_release
        with:
          semantic_version: 23.0.2
          dry_run: true
          ci: false
          branches: |
            [
              '${{github.ref_name}}'
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Print new version
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: |
          if [ "${{steps.dry_release.outputs.last_release_version}}" != "" ]; then
            echo "Update module version in locals.tf to ${{steps.dry_release.outputs.new_release_version}}."
          else
            echo "No version update."
          fi
